export const categories = [
  { id: '1', name: 'Burgers', slug: 'burgers', description: 'Juicy handcrafted burgers', image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80' },
  { id: '2', name: 'Pizza', slug: 'pizza', description: 'Premium stone-baked pizzas', image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80' },
  { id: '3', name: 'Healthy Bowls', slug: 'healthy-bowls', description: 'Fresh, light, and balanced meals', image_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80' }
];

export const products = [
  {
    id: 'p1',
    slug: 'truffle-smash-burger',
    name: 'Truffle Smash Burger',
    category: 'Burgers',
    description: 'Double patty, truffle aioli, caramelized onions, and sharp cheddar.',
    price: 18.5,
    rating: 4.8,
    badge: 'HOT',
    image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    trending: true,
    best_seller: true,
    healthy: false,
    stock: 18
  },
  {
    id: 'p2',
    slug: 'neapolitan-margherita',
    name: 'Neapolitan Margherita',
    category: 'Pizza',
    description: 'Slow-fermented crust, basil, tomato, and fresh mozzarella.',
    price: 16.25,
    rating: 4.7,
    badge: 'PREMIUM',
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    trending: false,
    best_seller: true,
    healthy: false,
    stock: 22
  },
  {
    id: 'p3',
    slug: 'protein-power-bowl',
    name: 'Protein Power Bowl',
    category: 'Healthy Bowls',
    description: 'Grilled chicken, quinoa, greens, avocado, and citrus dressing.',
    price: 14.9,
    rating: 4.9,
    badge: 'HEALTHY',
    image_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: true,
    best_seller: false,
    healthy: true,
    stock: 11
  },
  {
    id: 'p4',
    slug: 'bbq-pulled-burger',
    name: 'BBQ Pulled Burger',
    category: 'Burgers',
    description: 'Slow-cooked pulled beef, smoky BBQ glaze, crunchy slaw.',
    price: 17.9,
    rating: 4.6,
    badge: 'SIGNATURE',
    image_url: 'https://images.unsplash.com/photo-1550317138-10000687a72b?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: true,
    best_seller: false,
    healthy: false,
    stock: 16
  },
  {
    id: 'p5',
    slug: 'pepperoni-luxe',
    name: 'Pepperoni Luxe',
    category: 'Pizza',
    description: 'Hand-tossed crust, rich tomato sauce, double pepperoni, basil.',
    price: 18.75,
    rating: 4.8,
    badge: 'BEST SELLER',
    image_url: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    trending: true,
    best_seller: true,
    healthy: false,
    stock: 20
  },
  {
    id: 'p6',
    slug: 'spinach-feta-pizza',
    name: 'Spinach Feta Pizza',
    category: 'Pizza',
    description: 'Roasted garlic cream, feta, spinach, mozzarella, chili oil.',
    price: 17.2,
    rating: 4.5,
    badge: 'NEW',
    image_url: 'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: false,
    best_seller: false,
    healthy: false,
    stock: 14
  },
  {
    id: 'p7',
    slug: 'greek-chicken-bowl',
    name: 'Greek Chicken Bowl',
    category: 'Healthy Bowls',
    description: 'Herb chicken, rice, cucumber, olives, feta, tzatziki.',
    price: 15.4,
    rating: 4.9,
    badge: 'FRESH',
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: true,
    best_seller: false,
    healthy: true,
    stock: 13
  },
  {
    id: 'p8',
    slug: 'salmon-avocado-bowl',
    name: 'Salmon Avocado Bowl',
    category: 'Healthy Bowls',
    description: 'Seared salmon, avocado, greens, sesame, and lemon soy.',
    price: 19.5,
    rating: 4.8,
    badge: 'PREMIUM',
    image_url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    trending: false,
    best_seller: false,
    healthy: true,
    stock: 9
  },
  {
    id: 'p9',
    slug: 'mango-passion-smoothie',
    name: 'Mango Passion Smoothie',
    category: 'Drinks',
    description: 'Fresh mango, passion fruit, yogurt, and honey.',
    price: 7.9,
    rating: 4.7,
    badge: 'REFRESH',
    image_url: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: false,
    best_seller: false,
    healthy: true,
    stock: 30
  },
  {
    id: 'p10',
    slug: 'iced-caramel-latte',
    name: 'Iced Caramel Latte',
    category: 'Drinks',
    description: 'Espresso, cold milk, caramel, and a hint of sea salt.',
    price: 6.95,
    rating: 4.6,
    badge: 'CLASSIC',
    image_url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: true,
    best_seller: false,
    healthy: false,
    stock: 26
  },
  {
    id: 'p11',
    slug: 'chocolate-fudge-cake',
    name: 'Chocolate Fudge Cake',
    category: 'Desserts',
    description: 'Rich chocolate layers, fudge ganache, cocoa crumble.',
    price: 8.5,
    rating: 4.9,
    badge: 'DESSERT',
    image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    trending: false,
    best_seller: true,
    healthy: false,
    stock: 12
  },
  {
    id: 'p12',
    slug: 'vanilla-burnt-cheesecake',
    name: 'Vanilla Burnt Cheesecake',
    category: 'Desserts',
    description: 'Silky center, caramelized top, and vanilla bean finish.',
    price: 8.2,
    rating: 4.8,
    badge: 'CHEF PICK',
    image_url: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: true,
    best_seller: false,
    healthy: false,
    stock: 10
  },
  {
    id: 'p13',
    slug: 'blackened-chicken-wrap',
    name: 'Blackened Chicken Wrap',
    category: 'Wraps',
    description: 'Grilled chicken, crisp lettuce, tomato, garlic aioli, and tortilla wrap.',
    price: 13.75,
    rating: 4.6,
    badge: 'NEW',
    image_url: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: true,
    best_seller: false,
    healthy: false,
    stock: 19
  },
  {
    id: 'p14',
    slug: 'shrimp-fried-rice',
    name: 'Shrimp Fried Rice',
    category: 'Asian',
    description: 'Jasmine rice, jumbo shrimp, egg, peas, scallions, soy glaze.',
    price: 16.4,
    rating: 4.7,
    badge: 'CHEF PICK',
    image_url: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    trending: false,
    best_seller: false,
    healthy: false,
    stock: 15
  },
  {
    id: 'p15',
    slug: 'teriyaki-salmon-rice-bowl',
    name: 'Teriyaki Salmon Rice Bowl',
    category: 'Asian',
    description: 'Teriyaki-glazed salmon, rice, edamame, cucumber, sesame.',
    price: 18.9,
    rating: 4.8,
    badge: 'PREMIUM',
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: true,
    best_seller: true,
    healthy: true,
    stock: 12
  },
  {
    id: 'p16',
    slug: 'beef-taco-trio',
    name: 'Beef Taco Trio',
    category: 'Tacos',
    description: 'Three soft tacos with spiced beef, salsa, pickled onion, and crema.',
    price: 14.2,
    rating: 4.5,
    badge: 'HOT',
    image_url: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: false,
    best_seller: false,
    healthy: false,
    stock: 21
  },
  {
    id: 'p17',
    slug: 'crispy-fish-sandwich',
    name: 'Crispy Fish Sandwich',
    category: 'Sandwiches',
    description: 'Crispy white fish, tartar sauce, lettuce, pickles, soft bun.',
    price: 15.1,
    rating: 4.6,
    badge: 'SIGNATURE',
    image_url: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: false,
    best_seller: false,
    healthy: false,
    stock: 17
  },
  {
    id: 'p18',
    slug: 'seafood-pasta-alfredo',
    name: 'Seafood Pasta Alfredo',
    category: 'Pasta',
    description: 'Creamy alfredo, linguine, prawns, calamari, parmesan, herbs.',
    price: 19.8,
    rating: 4.9,
    badge: 'PREMIUM',
    image_url: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    trending: true,
    best_seller: true,
    healthy: false,
    stock: 8
  },
  {
    id: 'p19',
    slug: 'spaghetti-bolognese',
    name: 'Spaghetti Bolognese',
    category: 'Pasta',
    description: 'Slow-simmered beef sauce, parmesan, basil, and al dente spaghetti.',
    price: 16.95,
    rating: 4.7,
    badge: 'CLASSIC',
    image_url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: true,
    best_seller: false,
    healthy: false,
    stock: 18
  },
  {
    id: 'p20',
    slug: 'chicken-caesar-salad',
    name: 'Chicken Caesar Salad',
    category: 'Salads',
    description: 'Romaine, grilled chicken, parmesan, croutons, caesar dressing.',
    price: 12.8,
    rating: 4.6,
    badge: 'LIGHT',
    image_url: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: false,
    best_seller: false,
    healthy: true,
    stock: 24
  },
  {
    id: 'p21',
    slug: 'bbq-chicken-wings',
    name: 'BBQ Chicken Wings',
    category: 'Snacks',
    description: 'Crispy wings tossed in smoky BBQ sauce with ranch dip.',
    price: 13.4,
    rating: 4.7,
    badge: 'SHAREABLE',
    image_url: 'https://plus.unsplash.com/premium_photo-1669742928112-19364a33b530?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: true,
    best_seller: false,
    healthy: false,
    stock: 20
  },
  {
    id: 'p22',
    slug: 'cheeseburger-deluxe',
    name: 'Cheeseburger Deluxe',
    category: 'Burgers',
    description: 'Beef patty, cheddar, lettuce, tomato, onion, house sauce.',
    price: 15.9,
    rating: 4.5,
    badge: 'CLASSIC',
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: false,
    best_seller: false,
    healthy: false,
    stock: 25
  },
  {
    id: 'p23',
    slug: 'meat-lovers-pizza',
    name: 'Meat Lovers Pizza',
    category: 'Pizza',
    description: 'Pepperoni, sausage, beef, mozzarella, and rich tomato sauce.',
    price: 19.25,
    rating: 4.8,
    badge: 'BEST SELLER',
    image_url: 'https://plus.unsplash.com/premium_photo-1733259709671-9dbf22bf02cc?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: true,
    best_seller: true,
    healthy: false,
    stock: 11
  },
  {
    id: 'p24',
    slug: 'strawberry-cheesecake-slice',
    name: 'Strawberry Cheesecake Slice',
    category: 'Desserts',
    description: 'Creamy cheesecake, strawberry glaze, and biscuit crust.',
    price: 7.95,
    rating: 4.8,
    badge: 'DESSERT',
    image_url: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: false,
    best_seller: false,
    healthy: false,
    stock: 14
  }
,
  {
    id: 'p25',
    slug: 'avocado-toast-deluxe',
    name: 'Avocado Toast Deluxe',
    category: 'Breakfast',
    description: 'Sourdough, smashed avocado, chili flakes, pea shoots, and lemon.',
    price: 11.5,
    rating: 4.7,
    badge: 'FRESH',
    image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: true,
    best_seller: false,
    healthy: true,
    stock: 20
  },
  {
    id: 'p26',
    slug: 'roasted-vegetable-panini',
    name: 'Roasted Vegetable Panini',
    category: 'Sandwiches',
    description: 'Grilled zucchini, peppers, goat cheese, pesto, pressed ciabatta.',
    price: 12.95,
    rating: 4.6,
    badge: 'VEGGIE',
    image_url: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: false,
    best_seller: false,
    healthy: true,
    stock: 18
  },
  {
    id: 'p27',
    slug: 'lamb-kebab-platter',
    name: 'Lamb Kebab Platter',
    category: 'Grill',
    description: 'Spiced lamb skewers, turmeric rice, salad, garlic yogurt.',
    price: 21.5,
    rating: 4.8,
    badge: 'SIGNATURE',
    image_url: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    trending: true,
    best_seller: false,
    healthy: false,
    stock: 9
  },
  {
    id: 'p28',
    slug: 'matcha-cheesecake',
    name: 'Matcha Cheesecake',
    category: 'Desserts',
    description: 'Silky matcha-infused cheesecake with sesame crumb.',
    price: 8.75,
    rating: 4.7,
    badge: 'NEW',
    image_url: 'https://plus.unsplash.com/premium_photo-1694599325857-24139cf22ace?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: true,
    best_seller: false,
    healthy: false,
    stock: 11
  },
  {
    id: 'p29',
    slug: 'kimchi-fried-rice',
    name: 'Kimchi Fried Rice',
    category: 'Asian',
    description: 'Gochujang-infused fried rice, kimchi, scallion, fried egg.',
    price: 13.9,
    rating: 4.6,
    badge: 'SPICY',
    image_url: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: false,
    best_seller: false,
    healthy: false,
    stock: 16
  },
  {
    id: 'p30',
    slug: 'buffalo-cauliflower-wings',
    name: 'Buffalo Cauliflower Wings',
    category: 'Snacks',
    description: 'Crispy cauliflower tossed in buffalo glaze with celery dip.',
    price: 10.5,
    rating: 4.5,
    badge: 'VEGAN',
    image_url: 'https://plus.unsplash.com/premium_photo-1664647731586-f7b3f08efd26?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: true,
    best_seller: false,
    healthy: true,
    stock: 22
  },
  {
    id: 'p31',
    slug: 'cajun-prawn-tacos',
    name: 'Cajun Prawn Tacos',
    category: 'Tacos',
    description: 'Sizzling prawns, mango salsa, cabbage slaw, lime crema.',
    price: 15.95,
    rating: 4.8,
    badge: 'FAVOURITE',
    image_url: 'https://plus.unsplash.com/premium_photo-1680293485552-80e2bcc5207b?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    trending: true,
    best_seller: false,
    healthy: false,
    stock: 13
  },
  {
    id: 'p32',
    slug: 'rosemary-garlic-fries',
    name: 'Rosemary Garlic Fries',
    category: 'Sides',
    description: 'Crispy fries tossed in rosemary, garlic, and parmesan.',
    price: 6.5,
    rating: 4.6,
    badge: 'SIDES',
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: false,
    best_seller: false,
    healthy: false,
    stock: 40
  },
  {
    id: 'p33',
    slug: 'peppercorn-steak-salad',
    name: 'Peppercorn Steak Salad',
    category: 'Salads',
    description: 'Seared steak, peppercorn dressing, mixed greens, heirloom tomatoes.',
    price: 20.0,
    rating: 4.8,
    badge: 'PREMIUM',
    image_url: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    trending: false,
    best_seller: false,
    healthy: true,
    stock: 10
  },
  {
    id: 'p34',
    slug: 'coconut-lime-panna-cotta',
    name: 'Coconut Lime Panna Cotta',
    category: 'Desserts',
    description: 'Silky coconut panna cotta with zesty lime curd and coconut brittle.',
    price: 8.25,
    rating: 4.7,
    badge: 'CHEF PICK',
    image_url: 'https://plus.unsplash.com/premium_photo-1713913281148-1098c675ff3a?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: true,
    best_seller: false,
    healthy: false,
    stock: 12
  },
  {
    id: 'p35',
    slug: 'espresso-martini',
    name: 'Espresso Martini',
    category: 'Drinks',
    description: 'Vodka, espresso, Kahlua, and a smooth crema top.',
    price: 11.0,
    rating: 4.9,
    badge: 'ALCOHOL',
    image_url: 'https://images.unsplash.com/photo-1510627498534-cf7e9002facc?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    trending: true,
    best_seller: false,
    healthy: false,
    stock: 25
  },
  {
    id: 'p36',
    slug: 'yellow-lentil-dhal',
    name: 'Yellow Lentil Dhal',
    category: 'Vegan',
    description: 'Slow-cooked yellow lentils, coconut, cumin, served with basmati rice.',
    price: 12.0,
    rating: 4.6,
    badge: 'VEGAN',
    image_url: 'https://plus.unsplash.com/premium_photo-1671130295987-13d3b3b4e9dc?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    trending: false,
    best_seller: false,
    healthy: true,
    stock: 18
  }
];

export const orders = [
  { id: 'o1', status: 'preparing', total: 42.5, created_at: '2026-05-11T10:00:00Z' },
  { id: 'o2', status: 'delivered', total: 29.0, created_at: '2026-05-10T18:30:00Z' }
];

export const revenueSeries = [
  { name: 'Mon', revenue: 1200 },
  { name: 'Tue', revenue: 1900 },
  { name: 'Wed', revenue: 1400 },
  { name: 'Thu', revenue: 2400 },
  { name: 'Fri', revenue: 3200 },
  { name: 'Sat', revenue: 4100 },
  { name: 'Sun', revenue: 3800 }
];